#server.port=8181
spring.datasource.url = jdbc:postgresql://localhost:5432/commercial
spring.datasource.username = postgres
spring.datasource.password = ***REMOVED***
spring.datasource.driverClassName = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true

spring.jackson.serialization.fail-on-empty-beans=false 
#============> en cas AJAX JSON probleme serialization

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB