server.port=8181
spring.datasource.url = jdbc:postgresql://localhost:5432/commercial
spring.datasource.username = postgres
spring.datasource.password = Admin125478
spring.datasource.driverClassName = org.postgresql.Driver

#server.error.whitelabel.enabled=false

spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true

#--------> en cas AJAX JSON probleme serialization

spring.jackson.serialization.fail-on-empty-beans=false 

#--------> en cas AJAX JSON probleme serialization

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

#-----------------------

spring.session.timeout = 30m
server.servlet.session.timeout=30m

#spring.datasource.hikari.maximum-pool-size=50
#spring.datasource.hikari.connection-timeout=3600000
#spring.datasource.hikari.idleTimeout=600000
#spring.datasource.hikari.minimumIdle=5
#spring.datasource.hikari.test-on-borrow=true
#spring.datasource.hikari.test-while-idle=true
#spring.datasource.hikari.time-between-eviction-runs-millis=3600000

#-----------------------